'use strict';

// FAQ data for FAQPage JSON-LD on aircraft and route landing pages.
// Mirror of the `faq` arrays in client/src/content/landingCopy.js.
// Keep in sync — the visible page and structured data must match,
// otherwise Google treats the rich result as policy-violating.

const AIRCRAFT_FAQ = {
  'boeing-737': [
    { q: 'How many passengers does the Boeing 737 carry?', a: 'It depends on the variant and configuration. A 737-800 or MAX 8 typically seats 162 to 189 in a two-class layout, or up to around 200 in a high-density single-class cabin. The smaller 737-700 and MAX 7 carry roughly 126 to 149 seats, while the stretched MAX 9 and MAX 10 reach 178 to 204 and 188 to 230 respectively.' },
    { q: "What's the range of a 737 MAX?", a: 'The MAX 8 has a range of about 3,500 nautical miles, which covers most transcontinental US routes and many transatlantic sectors from the US East Coast to Western Europe. The longer-range MAX 8 ER and MAX 10 push closer to 3,300 to 3,800 nautical miles depending on payload, enough for routes like New York to Rome or Los Angeles to Honolulu with full passenger loads.' },
    { q: 'Is the 737 still flying in 2026?', a: 'Yes, very much so. The NG family (737-700/800/900) is still in service across most major and low-cost carriers, and the MAX family is in full production and continued deliveries. Between NG and MAX variants, the 737 remains the single most-produced and most-flown airliner worldwide, with thousands of daily departures.' },
  ],
  'boeing-757': [
    { q: 'Is the Boeing 757 still flying in 2026?', a: 'Yes, though fleets are shrinking each year. Delta, United, and Icelandair remain significant passenger operators, and FedEx flies a large 757 freighter fleet. The A321neo and A321XLR are the most common replacements on passenger routes, so expect retirements to continue into the late 2020s, particularly for the older -200s.' },
    { q: 'Why do airlines use the 757 on transatlantic routes?', a: 'The 757-200 has range around 3,900 nautical miles and strong climb performance, which lets it fly routes from the US East Coast to Western Europe with a full passenger load. Its single-aisle operating cost is significantly lower than a wide-body, making it ideal for thin transatlantic markets that could not profitably support a 767 or 787.' },
    { q: 'How many passengers does the 757 carry?', a: 'A typical two-class 757-200 seats 180 to 200 passengers, with charter layouts reaching around 230. The stretched 757-300 carries up to about 243 in a two-class configuration and was used mostly by leisure and holiday operators rather than legacy carriers.' },
  ],
  'boeing-767': [
    { q: 'Is the 767 still flying passengers in 2026?', a: 'Yes, primarily with Delta and United on transatlantic and Latin America routes. Several other legacy carriers continue to operate a small number. Most airlines are transitioning to the 787-9 or A330-900neo, so passenger 767 service is shrinking year over year, while freight variants remain in full production.' },
    { q: "What's the typical cabin layout on a 767?", a: 'On Delta and United the 767-300ER and 767-400ER carry 200 to 240 passengers across Delta One or Polaris business class, premium economy, and economy, in a 2-3-2 economy cabin. That 2-3-2 layout is a passenger favorite because two thirds of seats are aisle or window, unlike most newer wide-bodies.' },
    { q: "What's the range of a 767-300ER?", a: 'Around 5,900 to 6,100 nautical miles with a full passenger load, enough to cover any North Atlantic route and most US to South America long-haul sectors. Extended-range versions have been used historically on routes up to about 12 hours block time, though modern twins like the 787 now fly further with better fuel economics.' },
  ],
  'boeing-777': [
    { q: 'How many passengers does the 777 carry?', a: 'The 777-300ER typically carries 300 to 396 passengers in a three-class layout depending on carrier configuration. Emirates in two classes can reach 427. The shorter 777-200ER seats around 280 to 320, and the upcoming 777-9 will carry roughly 400 to 425 in a standard three-class cabin.' },
    { q: "What's the range of a 777-300ER?", a: 'About 7,300 nautical miles, roughly 14 hours of flying, which covers virtually any city pair in the world with one stop at most. The 777-200LR variant extends that to approximately 8,500 nautical miles and has been used on ultra-long routes like Newark to Singapore in earlier years.' },
    { q: 'Is business class on the 777 any good?', a: 'Quality varies widely by airline. Qatar Qsuite on the 777 is considered one of the best business products in the world, with fully enclosed suites. Emirates, Singapore, Cathay, and ANA also offer well-regarded business cabins. Legacy US carriers have generally upgraded their 777 business cabins to fully flat, direct-aisle-access seats over the past several years.' },
  ],
  'boeing-787': [
    { q: 'How many passengers fit on a 787?', a: 'It varies by variant. The 787-8 typically seats 240 to 260 in three classes. The 787-9, the most common variant, carries 270 to 310. The stretched 787-10 reaches 320 to 350 in three classes, or around 380 in denser two-class configurations used by some Asian carriers on regional trunk routes.' },
    { q: "What's different about the 787 cabin experience?", a: 'The 787 pressurizes to a lower cabin altitude of about 6,000 feet instead of the traditional 8,000 feet, and maintains higher cabin humidity. That reduces dehydration and jetlag on long flights. Windows are larger than on comparable wide-bodies, with electrochromic dimming instead of pull-down shades, and the cabin noise level is noticeably lower.' },
    { q: "What's the range of the 787-9?", a: 'Around 7,500 nautical miles, which covers city pairs like London to Perth, New York to Manila, or Los Angeles to Singapore. That range is what has let airlines open ultra-long-haul thin routes, since the 787 economics work with smaller passenger loads that would not support a larger 777 or A350.' },
  ],
  'boeing-747': [
    { q: 'Is the 747 still flying passengers in 2026?', a: 'Barely, and on a limited number of routes. Lufthansa is the only major operator actively scheduling the 747-8I on long-haul, mostly out of Frankfurt. A very small number of other carriers retain 747-400s for specific uses. Passenger 747 flying is expected to continue shrinking as legacy airframes reach retirement age.' },
    { q: 'Can I still book a 747 flight?', a: 'Yes, if you pick routes operated by Lufthansa out of Frankfurt with the 747-8I, or a handful of other niche services. Equipment swaps do happen, so to guarantee the experience check the aircraft type at booking and again 24 hours before departure. The upper-deck business cabin is a long-time enthusiast favorite on the 747-8I.' },
    { q: 'How many passengers did the 747 carry?', a: "A typical three-class 747-400 carried around 416 passengers. The 747-8I seats approximately 410 in three classes or up to 467 in denser configurations. High-density charter 747-400 layouts historically reached 580 or more, though those configurations are no longer common in regular passenger service." },
  ],
  'airbus-a340': [
    { q: 'Is the A340 still flying in 2026?', a: 'Only in small numbers. Lufthansa and SWISS retain limited A340 fleets, and a handful of other carriers still operate isolated frames. Most major operators have already retired the type in favor of the A350 or 787. If an A340 matters to you, check the operating aircraft at booking and again close to departure, since equipment swaps are common.' },
    { q: 'Why is the A340 being retired?', a: 'Four-engine fuel burn cannot compete with modern twins like the 777, 787, or A350 on the same routes. Once ETOPS rules made long overwater twin-engine flying routine, the economic case for four engines on passenger long-haul disappeared. Maintenance cost per seat-mile is also significantly higher, which is why fleets have shrunk so quickly.' },
    { q: 'How many passengers does the A340 carry?', a: 'The A340-300 typically seats 260 to 295 in three classes. The longer A340-600 carries roughly 320 to 380 in three classes and was historically used on high-demand long-haul routes. Range is around 7,400 nautical miles for the -300 and about 7,900 for the -600 depending on payload.' },
  ],
  'airbus-a220': [
    { q: 'How many passengers does the A220 carry?', a: 'The smaller A220-100 seats about 100 to 120 in typical two-class configurations. The A220-300, which most operators prefer, carries roughly 130 to 150. High-density single-class A220-300 layouts can reach around 160 seats, and most carriers fit a standard 3-2 economy with 5-across seating that is unusually wide for a narrow-body.' },
    { q: 'Is the A220 a regional or mainline aircraft?', a: 'It straddles both. Range up to about 3,300 nautical miles on the A220-300 and mainline-grade cabin standards make it capable of routes like New York to Los Angeles or long European legs, while its smaller capacity makes it economical on thinner markets that cannot fill a larger A320. Most operators treat it as mainline equipment, not regional.' },
    { q: 'What does the cabin feel like?', a: 'Cabin is noticeably quieter than older narrow-bodies thanks to the geared turbofan engines, and the 2-3 economy layout means roughly 60% of seats are aisle or window. Overhead bins are sized for full-size carry-on roller bags, and windows are larger than on an A320 or 737, which makes the cabin feel more spacious in practice.' },
  ],
  'airbus-a319': [
    { q: "What's the difference between the A319 and A320?", a: 'The A319 is about 3.7 meters shorter than the A320, which translates to roughly 30 fewer seats in a typical layout. Range is similar on both variants. From a passenger perspective the cabin looks the same, just shorter. Pilots fly both interchangeably thanks to a common type rating across the entire A320 family.' },
    { q: 'Is the A319 still being produced?', a: 'The A319neo is technically still offered but receives very few orders since most operators prefer the larger A320neo and A321neo for better per-seat economics. Production is effectively minimal. Existing A319ceo fleets are expected to continue in service well into the 2030s before replacement, particularly at US legacy carriers where the variant fits thinner routes.' },
    { q: 'How many passengers does the A319 carry?', a: 'About 124 to 150 in two-class configurations common at legacy carriers, and up to around 156 in a high-density single-class layout. Exit-limit is typically 156 passengers on the standard door configuration. Cabin comfort is identical to the A320 per seat, just with fewer rows and a shorter aisle.' },
  ],
  'airbus-a320': [
    { q: 'How many passengers does the A320 carry?', a: 'About 150 to 180 in typical two-class or single-class configurations. Low-cost carriers often fit 180 seats in a high-density layout. Legacy carriers with business or premium economy cabins usually carry 140 to 162. The A320neo has the same passenger capacity as the ceo, the difference is in engines and fuel burn.' },
    { q: "What's the A320neo?", a: 'The neo (new engine option) is the current-generation A320 re-engined with either CFM LEAP or Pratt and Whitney PW1100G geared turbofans. It burns around 15% less fuel per seat than the older ceo and includes sharklet wingtips. Range is slightly extended to about 3,500 nautical miles, and passengers experience a quieter cabin and newer interior standard.' },
    { q: 'Is the A320 still being produced?', a: 'Yes, in large volumes. The A320neo family is one of the highest-rate production aircraft lines in the world, with a very long order backlog stretching well into the 2030s. Production ramp-up is a primary focus for Airbus, and supply chain constraints in recent years have been the main bottleneck on delivery rate rather than demand.' },
  ],
  'airbus-a321': [
    { q: "What's the A321XLR?", a: 'The XLR is the longest-range A321 variant, with a rear center auxiliary fuel tank that extends range to around 4,700 to 4,900 nautical miles. That opens transatlantic and many long narrow-body routes such as smaller European cities to the US East Coast, or longer intra-Asia legs. Service entry began meaningfully in the mid-2020s, and orders are strong across North America and Europe.' },
    { q: 'How many passengers does the A321 carry?', a: 'Typical two-class A321neo layouts carry 180 to 220 seats. Low-cost single-class A321 configurations reach around 240. Transatlantic A321LR and XLR layouts with flat-bed business class typically seat about 165 to 180 due to the larger premium cabin. Exit-limit depends on door configuration and usually caps around 244 on the standard layout.' },
    { q: 'Can the A321XLR really replace wide-bodies on transatlantic routes?', a: 'On thin transatlantic markets, yes. It will not replace a 777 or A350 on high-demand routes like London to New York that need hundreds of seats. But for city pairs that generate roughly 150 to 180 daily passengers each way, like secondary European cities to the US East Coast, the XLR makes year-round service economically viable where a wide-body would not fill.' },
  ],
  'airbus-a320-family': [
    { q: "What's the difference between the A318, A319, A320, and A321?", a: 'Fuselage length and seat count. The A318 is the shortest at around 107 seats (rarely used today), then the A319 at about 124 to 156, the A320 at 150 to 180, and the A321 at 180 to 240. All share a common type rating, which means pilots trained on one can fly any of them with only short differences training. Systems and cockpits are nearly identical.' },
    { q: 'Is the A318 still flying?', a: 'Very rarely. A small number remain in service for niche operations, but the variant never sold in volume and most have been retired. Air France and British Airways previously used the A318 for specialty city-pair flying, but those configurations are no longer regularly scheduled. Most passengers will never fly one.' },
    { q: 'Why do airlines mix A320-family variants?', a: 'Because the common type rating lets one pilot pool fly multiple sizes, airlines can match aircraft size to demand on each route without multiplying training and operational cost. A thin route gets an A319, a medium route gets an A320, a busy trunk or long leg gets an A321. That flexibility is a major structural advantage of the family.' },
  ],
  'airbus-a330': [
    { q: "What's the difference between the A330ceo and A330neo?", a: 'The neo uses Rolls-Royce Trent 7000 engines, new Sharklets, and an updated cabin, giving roughly 14% better fuel burn per seat. Range on the A330-900 extends to around 7,200 nautical miles compared to about 6,350 on the A330-300ceo. Cabin standard is newer with larger overhead bins and the Airspace interior used on the A350.' },
    { q: 'How many passengers does the A330 carry?', a: 'The A330-200 and A330-800 typically seat 240 to 260 in three classes. The A330-300 and A330-900 carry roughly 280 to 310 in three classes, or up to around 440 in dense two-class leisure configurations. Most legacy operators run three-class layouts with flat-bed business, premium economy, and a 2-4-2 economy cabin.' },
    { q: "What's the A330 used for today?", a: 'Medium and long-haul twin-aisle routes that do not need a 787 or A350 capacity level. Common roles include transatlantic flying, intra-Asia long legs, Middle East to Europe, and Pacific service. It also appears frequently in leisure and charter markets where operating cost per seat matters more than absolute fuel burn, and the A330-900 is the dominant variant on new orders.' },
  ],
  'airbus-a350': [
    { q: "What's the range of the A350?", a: "The A350-900 has a range of about 8,100 nautical miles and the A350-1000 about 8,700. The ultra-long-range A350-900ULR extends that to over 9,500 nautical miles, enough for Singapore to Newark nonstop, which is currently the world's longest scheduled commercial route at around 18.5 hours of flight time." },
    { q: "What's the cabin experience on the A350?", a: 'Similar to the 787: lower cabin altitude around 6,000 feet, higher humidity, quieter cabin, and larger windows. Most operators run three-class cabins with flat-bed business, premium economy, and a 3-3-3 economy layout. Some carriers have installed 3-4-3 economy but the aircraft was designed for 3-3-3. The Airspace cabin standard features mood lighting and larger overhead bins.' },
    { q: 'How many passengers does the A350 carry?', a: "The A350-900 typically seats 300 to 350 in three classes. The A350-1000 carries roughly 350 to 410. Ultra-dense leisure layouts can push higher, though most customers fly the type in premium-heavy three-class configurations. Singapore Airlines' A350-900ULR is configured for only 161 business and premium economy seats for maximum ultra-long-haul comfort." },
  ],
  'airbus-a380': [
    { q: 'Is the A380 still flying in 2026?', a: 'Yes. Emirates, British Airways, Qantas, Singapore Airlines, Lufthansa, Korean Air, ANA, Qatar, and Etihad all operate the A380 on selected high-demand routes. Production has ended, but the existing fleet is in full service and expected to continue flying well into the 2030s on routes where its capacity advantages matter, particularly at slot-constrained airports.' },
    { q: "What's the A380 cabin experience like?", a: 'Spacious and quiet. Economy is typically 3-4-3 on the main deck, but the cabin feels wider than a 777 or A350. Business class is on the upper deck with 1-2-1 layouts on most carriers. Emirates offers showers in first class and an onboard lounge; Etihad previously offered The Residence. The staircase between decks is a signature A380 feature.' },
    { q: 'How many passengers does the A380 carry?', a: "A typical four-class layout carries 450 to 550 passengers. Emirates two-class leisure configurations reach about 615. Theoretical single-class maximum is around 853 but no operator uses that layout. The aircraft's appeal is partly that airlines generally configure it with generous premium cabins rather than maximum-density seating." },
  ],
  'embraer-e170-e175': [
    { q: "What's the 2-2 seating layout like?", a: 'Every seat is either an aisle or a window. There are no middle seats. The cabin is narrower than a mainline narrow-body but the seat-pair layout is widely considered the most comfortable part of the E170/E175 experience, particularly compared to the 1-2 or 2-2 layouts on older regional jets like the CRJ series or Embraer ERJ-145.' },
    { q: "What's the difference between the E170, E175, and E190?", a: 'Fuselage length and passenger capacity. The E170 seats about 70 to 78, the E175 about 76 to 88, the E190 about 96 to 114, and the E195 about 108 to 124. All share a common type rating and similar cabin width. The E170 and E175 are regional-focused, while the E190 and E195 are small-mainline.' },
    { q: 'Why is the E175 so common at US carriers?', a: 'Pilot scope clauses at the three major US legacy carriers (American, Delta, United) limit regional aircraft to 76 seats and 86,000 pound maximum takeoff weight. The E175 fits those limits precisely, making it the standard aircraft for regional subsidiary flying. The newer E175-E2 exceeds those limits and has therefore not been ordered in meaningful volume by US majors.' },
  ],
  'embraer-e190-e195': [
    { q: "What's the E2 and how is it different?", a: 'The E190-E2 and E195-E2 are re-engined with Pratt and Whitney PW1900G geared turbofans plus a new wing. Fuel burn is roughly 17% lower per seat than the E1 generation, and the aircraft is quieter. Range extends to around 2,800 nautical miles on the E195-E2. Cabin standard is newer with larger overhead bins, and the windows are slightly larger.' },
    { q: 'How many passengers do the E190 and E195 carry?', a: 'The E190 seats around 96 to 114 depending on configuration. The larger E195 carries about 108 to 124 in single-class layouts. The E195-E2 reaches up to 146 in high-density configurations. All versions use a 2-2 cabin with every seat either aisle or window, which is a notable passenger comfort advantage over 3-3 narrow-bodies.' },
    { q: 'Is the E190/E195 considered mainline or regional?', a: 'It depends on the operator. In Europe, KLM Cityhopper and similar carriers treat it as mainline feeder equipment. In the United States, regional scope clauses limit the E190 from being used in large numbers since it exceeds 76 seats. Breeze Airways uses the E190 and E195 as low-cost mainline equipment on point-to-point underserved routes.' },
  ],
  'bombardier-crj': [
    { q: "What's the difference between the CRJ variants?", a: 'Fuselage length and capacity. The CRJ-200 seats 50, the CRJ-700 seats 66 to 78, the CRJ-900 seats 76 to 90, and the CRJ-1000 seats 97 to 104. The CRJ-700 and later variants share a common type rating. The CRJ-200 is a much older design and is being progressively retired across most fleets.' },
    { q: 'Is the CRJ still being produced?', a: 'No. Bombardier sold the CRJ program to Mitsubishi Heavy Industries, and production ended in the early 2020s. The existing fleet continues to operate at regional carriers in North America and Europe, but new deliveries are not happening. Replacements at most US regional carriers are E175s, which have a larger cabin and better passenger comfort.' },
    { q: 'Why is the CRJ cabin so tight?', a: 'The CRJ is derived from the Challenger business jet, so fuselage diameter is smaller than the Embraer E-Jet. Overhead bin space is very limited, and many full-size carry-on bags have to be gate-checked. Cabin ceiling is low enough that tall passengers often have to stoop in the aisle. It remains in service largely because operators already own the fleet, not because passengers prefer it.' },
  ],
  'bombardier-dash-8': [
    { q: "What's it like to fly on a Q400?", a: 'The cabin is narrower than a jet, with 2-2 seating and overhead bins sized only for small carry-ons. Noise is higher than a jet due to the propellers, though the Q400 uses active noise cancellation and is noticeably quieter than older turboprops. Flight times on typical 300 nautical mile routes are 45 to 60 minutes. Descent and approach can feel more active than a jet.' },
    { q: 'Is the Dash 8 still being produced?', a: 'Production was suspended in the early 2020s after De Havilland Canada moved the program out of Downsview in Toronto. The company has indicated plans to restart Q400 production at a new facility, though timing remains uncertain. The existing fleet continues to operate actively, and backlogs of parts support continued service for years to come.' },
    { q: 'Why do some airlines still use turboprops?', a: 'Fuel burn per seat on sub-400 nautical mile routes is significantly better than any regional jet. Turboprops also handle short runways and some high-elevation or hot-climate airports better than equivalent jets. For very short sectors, their block times are comparable to jets once you include climb and descent. That combination keeps them economical on thin, short regional routes.' },
  ],
  'atr-42-72': [
    { q: "What's the difference between the ATR 42 and ATR 72?", a: 'Size. The ATR 42 seats about 48 passengers and the ATR 72 seats 70 to 78. They share a common type rating, so pilots can fly both with minimal differences training. Most fleets prefer the larger ATR 72 for per-seat economics, but the ATR 42 remains useful on very thin routes or airports with limited infrastructure where a smaller airframe is required.' },
    { q: "What's the flight experience like?", a: 'Cabin is 2-2 seating with no middle seats, noise from the propellers is higher than a jet though newer aircraft have noise insulation, and flight times are short, usually under 90 minutes. Overhead bins are small, so roller bags typically get gate-checked. The aircraft handles short runways well and can operate into airports that would not accept a regional jet at maximum payload.' },
    { q: 'Why are turboprops used for short routes?', a: 'Fuel burn per seat on routes under 400 nautical miles is the lowest of any regional aircraft in production. Block times on short sectors are comparable to regional jets once you include climb and descent time. Turboprops also handle short runways, hot-and-high airports, and unpaved strips better than equivalent jets, which keeps them irreplaceable on many island, developing-country, and remote regional networks.' },
  ],
};

// Route FAQ uses template strings substituted at render time with
// {from.city}, {from.iata}, {to.city}, {to.iata}.
const ROUTE_FAQ = [
  { q: 'How long does the flight from {from.city} to {to.city} take?', a: 'Flight time from {from.city} ({from.iata}) to {to.city} ({to.iata}) depends on routing, aircraft type, and whether the flight is direct or connecting. A direct flight typically reflects great-circle distance plus winds, while one-stop options can add several hours depending on the layover airport. Check the exact duration in the search results above, where we show block time per itinerary along with stop count.' },
  { q: 'Which airlines fly from {from.city} to {to.city}?', a: 'Airline availability for {from.iata} to {to.iata} changes by season and sometimes week to week as carriers adjust capacity. Our search above pulls live schedules and returns the airlines currently selling this route, both direct and connecting. Codeshare and interline itineraries are included, so you may see results operated by one carrier but sold by another.' },
  { q: 'Are there direct flights from {from.city} to {to.city}?', a: 'Direct (nonstop) availability on {from.iata} to {to.iata} varies by date, day of week, and season. Busy city pairs usually have multiple daily nonstops, while thinner routes may only have direct service a few days per week or only during peak seasons. Use our search above with flexible dates to see which days actually have nonstop options.' },
  { q: 'What is the cheapest month to fly from {from.city} to {to.city}?', a: 'Prices on {from.iata} to {to.iata} shift with seasonality, school holidays, and major events at both ends. Our 12-month price calendar below the search results shows the lowest fare found per departure date, which makes it easy to spot the cheapest weeks at a glance. Flexibility of a few days around your target date often unlocks significantly lower fares.' },
];

function interpolate(tpl, from, to) {
  return tpl
    .replace(/\{from\.city\}/g, from.city)
    .replace(/\{from\.iata\}/g, from.iata)
    .replace(/\{to\.city\}/g, to.city)
    .replace(/\{to\.iata\}/g, to.iata);
}

module.exports = { AIRCRAFT_FAQ, ROUTE_FAQ, interpolate };
