const airportToCountry = {
  'LIS': 'Portugal',
  'NYC': 'United States',
  'JFK': 'United States',
  'EWR': 'United States',
  'LAX': 'United States',
  'ORD': 'United States',
  'MIA': 'United States',
  'LON': 'United Kingdom',
  'LHR': 'United Kingdom',
  'LGW': 'United Kingdom',
  'CDG': 'France',
  'ORY': 'France',
  'AMS': 'Netherlands',
  'FRA': 'Germany',
  'MUC': 'Germany',
  'BER': 'Germany',
  'MAD': 'Spain',
  'BCN': 'Spain',
  'FCO': 'Italy',
  'MXP': 'Italy',
  'ZRH': 'Switzerland',
  'VIE': 'Austria',
  'BRU': 'Belgium',
  'CPH': 'Denmark',
  'ARN': 'Sweden',
  'OSL': 'Norway',
  'HEL': 'Finland',
  'DUB': 'Ireland',
  'ATH': 'Greece',
  'IST': 'Turkey',
  'DME': 'Russia',
  'SVO': 'Russia',
  'DXB': 'United Arab Emirates',
  'SIN': 'Singapore',
  'HKG': 'Hong Kong',
  'NRT': 'Japan',
  'PEK': 'China',
  'PVG': 'China',
  'SYD': 'Australia',
  'GRU': 'Brazil',
  'EZE': 'Argentina',
  'BOG': 'Colombia',
  'MEX': 'Mexico',
  'YYZ': 'Canada',
  'YUL': 'Canada',
};

module.exports = { airportToCountry };
